/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FirstPage.java
 *
 * Created on 17-Nov-2011, 15:24:32
 */

package implementation;

import java.sql.*;

/**
 *
 * @author aa27927
 */
public class FirstPage extends javax.swing.JFrame {

    Main main;
    

    /** Creates new form FirstPage */
    public FirstPage(Main m) {
        main = m;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabelName1 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/implementation/banner.JPG"))); // NOI18N
        jLabel1.setBounds(0, 0, 400, 300);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnLogin.setText("Begin the test!");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.setBounds(250, 270, 140, 23);
        jLayeredPane1.add(btnLogin, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabelName1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName1.setText("Name:");
        jLabelName1.setBounds(90, 110, 50, 17);
        jLayeredPane1.add(jLabelName1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jTxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserNameActionPerformed(evt);
            }
        });
        jTxtUserName.setBounds(140, 110, 170, 20);
        jLayeredPane1.add(jTxtUserName, javax.swing.JLayeredPane.PALETTE_LAYER);

        lblMessage.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setBounds(140, 140, 170, 20);
        jLayeredPane1.add(lblMessage, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        if(jTxtUserName.getText().matches("\\w+ \\w+")){
            main.secondPage.setEnabled(true);
            tryLogin();
            this.dispose();
        } else {
            lblMessage.setText("Input your Name, please!");
        }
    }
   private void tryLogin() 
    {
        try{
            //connect to the database
              ConnectDatabase.init();
              Connection conn = ConnectDatabase.getConnection();
        
              //enable SQL statements to be created and run
              Statement stmt= conn.createStatement();	
                
              //retrieve login fields from interface
              String user = jTxtUserName.getText();   
        
              stmt.execute("INSERT INTO NYIMASDATABASE (NAME) VALUES ('"+user+"')");   
              
              
              stmt.close();
              conn.close();
            }
            catch (Exception ex)
            {
                System.err.print("SQLException: ");
		System.err.println(ex.getMessage());
            }
        
     
            
}//GEN-LAST:event_btnLoginActionPerformed

    private void jTxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables

}
