/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScorePage.java
 *
 * Created on 15-Dec-2011, 16:39:19
 */
package implementation;

/**
 *
 * @author aa27927
 */
public class ScorePage extends javax.swing.JFrame {
    Main main;
    /** Creates new form ScorePage */
    public ScorePage(Main m) {
        main = m;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        welldonelbl = new javax.swing.JLabel();
        scoreis = new javax.swing.JLabel();
        exitbtn1 = new javax.swing.JButton();
        Namelbl = new javax.swing.JLabel();
        scorelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welldonelbl.setFont(new java.awt.Font("Chiller", 2, 48));
        welldonelbl.setText("Well done! ");
        welldonelbl.setBounds(100, 10, 164, 56);
        jLayeredPane1.add(welldonelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        scoreis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scoreis.setText("your score is");
        scoreis.setBounds(160, 160, 87, 17);
        jLayeredPane1.add(scoreis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exitbtn1.setText("Exit");
        exitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtn1ActionPerformed(evt);
            }
        });
        exitbtn1.setBounds(331, 250, 60, 23);
        jLayeredPane1.add(exitbtn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Namelbl.setFont(new java.awt.Font("Tahoma", 1, 14));
        Namelbl.setText("John Connor");
        Namelbl.setBounds(60, 160, 100, 17);
        jLayeredPane1.add(Namelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        scorelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scorelbl.setText(String.valueOf((100*main.score)/15) + "%");
        scorelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scorelblMouseClicked(evt);
            }
        });
        scorelbl.setBounds(270, 160, 130, 17);
        jLayeredPane1.add(scorelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/implementation/thumbs.jpg"))); // NOI18N
        jLabel1.setBounds(0, -10, 400, 300);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbtn1ActionPerformed

    private void scorelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scorelblMouseClicked
        // TODO add your handling code here:z
    }//GEN-LAST:event_scorelblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namelbl;
    private javax.swing.JButton exitbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel scoreis;
    private javax.swing.JLabel scorelbl;
    private javax.swing.JLabel welldonelbl;
    // End of variables declaration//GEN-END:variables
}
