/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SecondQuestion.java
 *
 * Created on 29-Nov-2011, 09:44:49
 */
package implementation;

/**
 *
 * @author aa27927
 */
public class SecondQuestion extends javax.swing.JFrame {
    Main main;
    boolean[] wrongs = new boolean[6];

    /** Creates new form SecondQuestion */
    private int question1counter = 0;
    private int question2counter = 0;
    private int question3counter = 0;
    private int question4counter = 0;
    private int question5counter = 0;
    private int question6counter = 0;
    public SecondQuestion(Main m) {
        main = m;
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea2Q2 = new javax.swing.JTextArea();
        Ans6Q2 = new javax.swing.JTextField();
        Ans5Q2 = new javax.swing.JTextField();
        Ans3Q2 = new javax.swing.JTextField();
        Ans4Q2 = new javax.swing.JTextField();
        Ans2Q2 = new javax.swing.JTextField();
        Ans1Q2 = new javax.swing.JTextField();
        AnsB1Q2 = new javax.swing.JButton();
        AnsB2Q2 = new javax.swing.JButton();
        AnsB3Q2 = new javax.swing.JButton();
        AnsB4Q2 = new javax.swing.JButton();
        AnsB5Q2 = new javax.swing.JButton();
        AnsB6Q2 = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Second Question");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setText("What happens to the power dissipated in the resistor when it is quadrupled and the voltage remains constant?");
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(8);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("The following choices refer to the questions below.\n(A)It is doubled \n(B)It is quadrupled  \n(C)It is halved  \n(D)It is quartered  \n(E)It remains the same\n(F)Current is same throught out the circuit\n(G)Voltage is same throught the circuit\t ");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField2.setText("How bright will the bulb in series if the current is quadrupled? ");
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField3.setText("What happens to the voltage across a series circuit if the supplied voltage is halved?  ");
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField4.setText("What happens to the current in series circuit if the current is quartered ? ");
        jTextField4.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField5.setText("If an ammeter in a series circuit reads a current of 2 ampere, what is the current throughout the circuit? ");

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField6.setText("What happens to the resistor when the voltage is doubled?  ");
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        TextArea2Q2.setColumns(20);
        TextArea2Q2.setEditable(false);
        TextArea2Q2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        TextArea2Q2.setRows(5);
        TextArea2Q2.setText("                                                               *{V = R × I} *{I = V / R} *{R = V / I}\n\n                               \t\t    The formulas of Ohm's Law\n                               Ohm's Law can be rewritten in three ways for calculating current, resistance, and voltage.If a\n\t\tcurrent I should flow through a resistor R, the voltage V canbe calculated.  \n                                      \t                                    V = R × I ");
        jScrollPane2.setViewportView(TextArea2Q2);

        AnsB1Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB1Q2ActionPerformed(evt);
            }
        });

        AnsB2Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB2Q2ActionPerformed(evt);
            }
        });

        AnsB3Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB3Q2ActionPerformed(evt);
            }
        });

        AnsB4Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB4Q2ActionPerformed(evt);
            }
        });

        AnsB5Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB5Q2ActionPerformed(evt);
            }
        });

        AnsB6Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsB6Q2ActionPerformed(evt);
            }
        });

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(769, 769, 769)
                        .addComponent(AnsB1Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans2Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans4Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(AnsB6Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(769, 769, 769)
                        .addComponent(AnsB2Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans6Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(769, 769, 769)
                        .addComponent(AnsB5Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans3Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(739, 739, 739)
                        .addComponent(NextButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(769, 769, 769)
                        .addComponent(AnsB4Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans5Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(Ans1Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(769, 769, 769)
                        .addComponent(AnsB3Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(AnsB1Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Ans2Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Ans4Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AnsB6Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(AnsB2Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(Ans6Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(AnsB5Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(Ans3Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(NextButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(AnsB4Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(Ans5Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(Ans1Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(AnsB3Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnsB1Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB1Q2ActionPerformed
        // Sets the text area to display the hint. Accepts both capital A and small letter a in Ans1Q2, then sets iself to un-editable.
        // Any other than a or A, it sets the the As1Q2 to ''try again'' and sets the textare to display some hints.
        // Adds 1 to the counter everytime you input other than a or A and click on the AnsB1Q2. when counter reacher 3, it sets the Ans1Q2 to A and un editable also
        // Sets AnsB1Q2 to uneditable.
        TextArea2Q2.setText("{V = R × I} *{I = V / R} *{R = V / I} *{P = V× I} Make use of all this forumalas,");
         if(Ans1Q2.getText().matches("a")|| Ans1Q2.getText().matches("A")){
            Ans1Q2.setText("Well done!");
            Ans1Q2.setEnabled(false);
            AnsB1Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[0]) main.score += 1;

        } else {
            Ans1Q2.setText("Try again.");
            TextArea2Q2.setText("HINT! Think about the forumla V=IR, Remmember that, V is proportional to I and R");
            question1counter += 1;
            if(question1counter == 3){
                wrongs[0] = true;
                Ans1Q2.setText("a");
                Ans1Q2.setEnabled(false);
                AnsB1Q2.setEnabled(false);
            }

         }
    }//GEN-LAST:event_AnsB1Q2ActionPerformed

    private void AnsB2Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB2Q2ActionPerformed
        // This codes will accepts both capital B and small letter b in Ans2Q2, then sets iself to un-editable.
        // Any other than b or B, it sets the the Ans2Q2 to ''try again'' and sets the textarea to display some hint.
        // Adds 1 to the counter everytime you input other than B or b and click on the AnsB2Q2. when counter reacher 3, it sets the Ans2Q2 to b and makes it un editable.
        // Sets AnsB2Q2 to uneditable.
        if(Ans2Q2.getText().matches("b")|| Ans2Q2.getText().matches("B")){
            Ans2Q2.setText("Well done!");
            Ans2Q2.setEnabled(false);
            AnsB2Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[1]) main.score += 1;
        }
        else {
            Ans2Q2.setText("Try again.");
             TextArea2Q2.setText("HINT! Think about the forumla {I = V / R} ");
             question2counter += 1;
             if(question2counter ==3){
                 wrongs[1] = true;
                Ans2Q2.setText("b");
                Ans2Q2.setEnabled(false);
                AnsB1Q2.setEnabled(false);
            }
           }
    }//GEN-LAST:event_AnsB2Q2ActionPerformed

    private void AnsB3Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB3Q2ActionPerformed
        // This codes will accepts both capital C and small letter c in Ans2Q2, then sets iself to un-editable.
        // Any other than c or C, it sets the the Ans3Q2 to ''try again'' and sets the textarea to display some hint.
        // Adds 1 to the counter everytime you input other than c or C and click on the AnsB3Q2. when counter reacher 3, it sets the Ans3Q2 to b and makes it un editable.
        // Sets AnsB3Q2 to uneditable.
        if(Ans3Q2.getText().matches("c")|| Ans3Q2.getText().matches("C")){
            Ans3Q2.setText("Well done!");
            Ans3Q2.setEnabled(false);
            AnsB3Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[2]) main.score += 1;
        }
        else {
            Ans3Q2.setText("Try again.");
             TextArea2Q2.setText("HINT! In series circuit, voltage is shared equally throughtout. ");
             question3counter += 1;
             if(question3counter ==3){
                 wrongs[2] = true;
                Ans3Q2.setText("c");
                Ans3Q2.setEnabled(false);
                AnsB3Q2.setEnabled(false);
            }
           }
    }//GEN-LAST:event_AnsB3Q2ActionPerformed

    private void AnsB4Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB4Q2ActionPerformed
        // This codes will accepts both capital D and small letter d in Ans2Q2, then sets iself to un-editable.
        // Any other than d or D, it sets the the Ans4Q2 to ''try again'' and sets the textarea to display some hint.
        // Adds 1 to the counter everytime you input other than d or D and click on the AnsB4Q2. when counter reacher 3, it sets the Ans4Q2 to b and makes it un editable.
        // Sets AnsB4Q2 to uneditable.
         if(Ans4Q2.getText().matches("d")|| Ans4Q2.getText().matches("D")){
            Ans4Q2.setText("Well done!");
            Ans4Q2.setEnabled(false);
            AnsB4Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[3]) main.score += 1;
        }
        else {
            Ans4Q2.setText("Try again.");
             TextArea2Q2.setText("HINT! In series circuit, Current is same throughout.");
             question4counter += 1;
             if(question4counter == 3){
                 wrongs[3] = true;
                Ans4Q2.setText("d");
                Ans4Q2.setEnabled(false);
                AnsB4Q2.setEnabled(false);
            }
           }
    }//GEN-LAST:event_AnsB4Q2ActionPerformed

    private void AnsB5Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB5Q2ActionPerformed
        // This codes will accepts both capital F and small letter f in Ans5Q2, then sets iself to un-editable.
        // Any other than f or F, it sets the the Ans5Q2 to ''try again'' and sets the textarea to display some hint.
        // Adds 1 to the counter everytime you input other than B or b and click on the AnsB1Q2. when counter reacher 3, it sets the Ans5Q2 to b and makes it un editable.
        // Sets AnsB5Q2 to uneditable.
          if(Ans5Q2.getText().matches("f")|| Ans5Q2.getText().matches("F")){
            Ans5Q2.setText("Well done!");
            Ans5Q2.setEnabled(false);
            AnsB5Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[4]) main.score += 1;
        }
        else {
            Ans5Q2.setText("Try again.");
             TextArea2Q2.setText("HINT! In series circuit, Current is same throughout. ");
             question5counter += 1;
             if(question5counter == 3){
                 wrongs[4] = true;
                Ans5Q2.setText("f");
                Ans5Q2.setEnabled(false);
                AnsB5Q2.setEnabled(false);
            }
         }
    }//GEN-LAST:event_AnsB5Q2ActionPerformed

    private void AnsB6Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsB6Q2ActionPerformed
        // This codes will accepts both capital D and small letter d in Ans6Q2, then sets iself to un-editable.
        // Any other than d or D, it sets the the Ans6Q2 to ''try again'' and sets the textarea to display some hint.
        // Adds 1 to the counter everytime you input other than B or b and click on the AnsB1Q2. when counter reacher 3, it sets the Ans6Q2 to b and makes it un editable.
        // Sets AnsB6Q2 to uneditable.
          if(Ans6Q2.getText().matches("d")|| Ans6Q2.getText().matches("D")){
            Ans6Q2.setText("Well done!");
            Ans6Q2.setEnabled(false);
            AnsB6Q2.setEnabled(false);
            //if it is not wrong, It will add one to the score
            if(!wrongs[5]) main.score += 1;
        }
        else {
            Ans6Q2.setText("Try again.");
             TextArea2Q2.setText("HINT! This question is a hard one, Therefore you have to use the forumal P = V × I ");
             question6counter += 1;
             if(question6counter == 3){
                wrongs[5] = true;
                Ans6Q2.setText("d");
                Ans6Q2.setEnabled(false);
                AnsB6Q2.setEnabled(false);
            }
           }
    }//GEN-LAST:event_AnsB6Q2ActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if(!Ans1Q2.isEnabled()&&!Ans2Q2.isEnabled()&&!Ans3Q2.isEnabled()
                &&!Ans4Q2.isEnabled() &&!Ans5Q2.isEnabled() &&!Ans6Q2.isEnabled()){
            new ThirdQuestion(main).setVisible(true);
            this.dispose();
            // This one checks if all the regions where you input your answer is set to un editable, if it is, then it
            // displays the Third question and closes the current page
        }
}//GEN-LAST:event_NextButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ans1Q2;
    private javax.swing.JTextField Ans2Q2;
    private javax.swing.JTextField Ans3Q2;
    private javax.swing.JTextField Ans4Q2;
    private javax.swing.JTextField Ans5Q2;
    private javax.swing.JTextField Ans6Q2;
    private javax.swing.JButton AnsB1Q2;
    private javax.swing.JButton AnsB2Q2;
    private javax.swing.JButton AnsB3Q2;
    private javax.swing.JButton AnsB4Q2;
    private javax.swing.JButton AnsB5Q2;
    private javax.swing.JButton AnsB6Q2;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextArea TextArea2Q2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
