/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SecondPage.java
 *
 * Created on 17-Nov-2011, 16:08:11
 */

package implementation;

/**
 *
 * @author aa27927
 */
public class SecondPage extends javax.swing.JFrame {
    Main main;
    /** Creates new form SecondPage */
    public SecondPage(Main m) {
        main = m;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButtonBegin2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Instructions");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(308, 29, 124, 33);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setText("1. This test is drag and drop Test based on circuits.");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 106, 779, 32);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField2.setText("2. There is 20 different questions, starting from the easiest question  and finishing with the hardest questions.");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 156, 779, 32);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField3.setText("3. Each question will have a different Circuit images and couple of options to choose from for your answer.");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(10, 206, 779, 32);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField4.setText("4. You drag the answer you think is right into the space given for it in the circuit.");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(10, 256, 779, 32);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField5.setText("5. You will have three chance to get the correct answer to drop in circuit, If you get it wrong three times then the correct");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(10, 306, 779, 32);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField6.setText(" answer will automatically pop-up.");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(10, 356, 779, 32);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField7.setText("6. At the end of all twenty questions, you will be marked and your score will be given out of twenty.");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(10, 406, 779, 32);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField8.setText("7. You wont be given any marks for the questions where the answer was given to you.");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(10, 456, 779, 32);

        jButtonBegin2.setText("Begin!");
        jButtonBegin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBegin2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBegin2);
        jButtonBegin2.setBounds(330, 550, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\aa27927\\Desktop\\Backgroundimage.PNG")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBegin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBegin2ActionPerformed
        // TODO add your handling code here:
        new FirstQuestion(main).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBegin2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBegin2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
